### ISSUE TITLE
Radiation Sources

### ISSUE THREAD

**Issue by allen-adastra** [google-deepmind/torax#28]
Excited to get my hands on this!

I noticed radiation sources aren't modeled yet. It seems Brems + Synchrotron radiation should be pretty simple to add; perhaps just using the same formulas as implemented in [cfspopcon](https://github.com/cfs-energy/cfspopcon/blob/main/cfspopcon/formulas/radiated_power/inherent.py)

Thoughts on me opening a PR as a simple starter task?

**Comment by jcitrin** [comment]
Bremsstrahlung added in #176 . Will keep this issue open for cyclotron and line radiation source discussions.

**Comment by jcitrin** [comment]
Closing this one. Will open separate ones later today for cyclotron radiation and line radiation
