### ISSUE TITLE
[bug] Simulation does not exit early when profiles become `nan`

### ISSUE THREAD

**Issue by theo-brown** [google-deepmind/torax#389]
I have a simulation that was running for ~1000 timesteps. However, all of the non-prescribed profiles become `nan` after 3 timesteps. It seems odd that that **didn't trigger an exit condition of some sort** - the simulation continued running for another ~997 timesteps, despite almost all of the profiles being `nan`.

I will upload a MWE of the config shortly. Note that as this was using a ST-like configuration, the QLKNN is expected to output nonsense, which is probably the cause of the `nan`s appearing in the first place; I'm not raising a bug about that, just that TORAX should exit in this case :)

**Comment by jcitrin** [comment]
Hi Theo. Thanks for exposing this. You are correct and the easiest thing to do will be to add a check following the exit of the stepper function, for NaNs or negative temperature/densities, and then trigger an error message and early exit of the simulation, while still writing out the (partial) output file for diagnostic/debugging purposes.

We'll put this in ASAP and test with your config once we have it.

**Comment by jcitrin** [comment]
Hi @theo-brown . Do you have the config available?

**Comment by jcitrin** [comment]
No worries, I made a different config that triggered NaNs. Will make the fix based on that

**Comment by jcitrin** [comment]
Fixed in !390. Please pull and try it out

**Comment by theo-brown** [comment]
Handles it nicely, thanks very much!
